// Stamp lib/version.ts with v{major}.{minor}.{commitCount}.
// Reads major.minor from package.json, count from `git rev-list --count HEAD`.
// Run via `npm run version:stamp` LOCALLY before committing.
// Don't run this on Vercel — CLI deploys lack .git, and a git-integration
// build would re-stamp with the same count we already wrote.
//
// We write count+1 because this stamp is meant for the COMMIT we're about
// to create (HEAD is currently the previous commit).

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const TARGET = "lib/version.ts";

function computeVersion() {
  const pkg = JSON.parse(readFileSync("package.json", "utf-8"));
  const [major, minor] = pkg.version.split(".");
  const currentCount = parseInt(
    execSync("git rev-list --count HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim(),
    10,
  );
  return `v${major}.${minor}.${currentCount + 1}`;
}

try {
  const version = computeVersion();
  const contents = `// Auto-generated by scripts/stamp-version.mjs — do not edit by hand.
// Updated by \`npm run version:stamp\` before each commit.
export const APP_VERSION = "${version}";
`;
  writeFileSync(TARGET, contents);
  console.log(`stamped ${TARGET} → ${version}`);
} catch (err) {
  console.warn(`version:stamp skipped (${err.message}); keeping ${TARGET} as-is.`);
  process.exit(0);
}
